---
info:
  title: Rex Java
  description: Rex Library for parsing Java serialized streams
  x-cortex-git:
    github:
      alias: r7org
      repository: rapid7/rex-java
  x-cortex-tag: rex-java
  x-cortex-type: service
  x-cortex-domain-parents:
  - tag: metasploit
openapi: 3.0.1
servers:
- url: "/"
